### ISSUE TITLE
Pi-hole keepalived chk_ftl script enhancement

### ISSUE THREAD

**Issue by Racerx323** [justinknguyen/Pi-Guide#1]
Thank you for the awesome guides. 

The script in the keepalived, step 6 guide only checks for the Pi-hole service. I wrote an enhanced script to check the status of the Pi-hole and Unbound service. If either service is unavailable on the primary server keepalived will fail over to secondary server. 

```
#!/bin/bash
STATUS=$(systemctl show -p ActiveState pihole-FTL | cut -d'=' -f2)
STATUS1=$(systemctl show -p ActiveState unbound | cut -d'=' -f2)

if [ "$STATUS" = "active" ] && [ "$STATUS1" = "active" ]
then
    exit 0
else
    exit 1
fi
```

**Comment by justinknguyen** [comment]
wow good catch! Thank you for contributing :) I'll update it now
